baseurl = "https://daltron.de/"
title = "gio54321"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

pagination.pagerSize = 20

# disqusShortname = "gio-d3141"

[markup.highlight]
style = "github-dark"

[params]
  author = "Giorgio Dell'Immagine"
  info = "Exploring computers: the weird part"
  description = "Exploring computers: the weird part"
  keywords = "blog,developer,personal,security,CTF"
  # avatarurl = "images/avatar.jpg"

  #gravatar = "john.doe@example.com"

  # faviconSVG = "/img/favicon.svg"
  # favicon_32 = "/img/favicon-32x32.png"
  # favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  #   category = "categories"
  series = "series"
  tag = "tags"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/gio54321/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/g_dellimmagine"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
